-- USE SCHEMA PUBLIC:

INSERT INTO CATEGORY (NAME) VALUES ('Main');
INSERT INTO CATEGORY (NAME) VALUES ('Reserve');
INSERT INTO CATEGORY (NAME) VALUES ('BASE');

INSERT INTO MANUFACTURER (NAME) VALUES ('Performance Design');
INSERT INTO MANUFACTURER (NAME) VALUES ('NZ Aerosport');
INSERT INTO MANUFACTURER (NAME) VALUES ('Squirrel');

INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (1, 'Katana', 2350.00);

INSERT INTO PARACHUTE (PRODUCT_ID, CELL, MANUFACTURER_ID) values (1, 9, 1);